all:
	g++ -I.. -L. *.cpp -fno-exceptions -Wall -Wextra -Werror -std=c++14 -O3 -lX11 -lGLEW -lGL -lGLU -lcubez -fopenmp

debug:
	g++ -I.. -L. *.cpp -fno-exceptions -Wall -Wextra -Werror -std=c++14 -ggdb -lX11 -lGLEW -lGL -lGLU -lcubez -fopenmp
